apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: default-pod-logs
  namespace: monitoring
  labels:
    grafana-agent-logs-instance: default
spec:
  pipelineStages:
    - docker: {}
  namespaceSelector:
    any: true
  selector:
    matchLabels: {}
