apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: istio-metrics-instance
  namespace: monitoring
  labels:
    grafana-agent: istio
spec:
  remoteWrite:
  - url: http://prometheus-operated:9090/api/v1/write
  # Reconcile all ServiceMonitors across all namespaces with a matching label.
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      grafana-agent-metrics-instance: istio

  # Reconcile all PodMonitors across all namespaces with a matching label.
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      grafana-agent-metrics-instance: istio

  # Reconcile all Probes across all namespaces with a matching label.
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      grafana-agent-metrics-instance: istio
