apiVersion: api.00rg.com/v1alpha1
kind: Wave
metadata:
  name: wave1
spec:
  hooks:
    preApply:
      # Before proceeding with the wave apply, wait until the metrics-server
      # is ready. If we don't do this, kubectl 1.26.0+ will produce a warning.
      waitForRollouts:
      - kube-system/metrics-server
