apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress-gateways
  namespace: istio-system
spec:
  profile: empty
  components:
    ingressGateways:
    - name: external-ingress-gateway
      namespace: istio-ingress
      enabled: true
      label:
        app: external-ingress-gateway
        istio: ingress-gateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
        service:
          type: NodePort
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 31000
    - name: internal-ingress-gateway
      namespace: istio-ingress
      enabled: true
      label:
        app: internal-ingress-gateway
        istio: ingress-gateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
        service:
          type: NodePort
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 31001
