apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress-gateways
  namespace: istio-system
spec:
  profile: empty
  components:
    ingressGateways:
    - name: external-ingress-gateway
      namespace: istio-ingress
      enabled: true
      label:
        app: external-ingress-gateway
        istio: ingress-gateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
        service:
          type: NodePort
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 31000
    - name: internal-ingress-gateway
      namespace: istio-ingress
      enabled: true
      label:
        app: internal-ingress-gateway
        istio: ingress-gateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
        service:
          type: NodePort
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 31001
    - name: office-ingress-gateway
      namespace: istio-ingress
      enabled: true
      label:
        app: office-ingress-gateway
        istio: ingress-gateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
        service:
          type: NodePort
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 31002
        podAnnotations:
          # Disable tracing for the office gateway as it just makes noise.
          proxy.istio.io/config: |
            tracing:
              enabled: false

  values:
    # Enable gateway injection. See:
    # https://github.com/istio/istio/issues/36670 and
    # https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
