apiVersion: api.00rg.com/v1alpha1
kind: Wave
metadata:
  name: wave3
spec:
  hooks:
    preApply:
      # waitForCRDs:
      # - gateways.networking.istio.io
      # - authorizationpolicies.security.istio.io
      # - requestauthentications.security.istio.io
      # - alertmanagerconfigs.monitoring.coreos.com
      # - alertmanagers.monitoring.coreos.com
      # - podmonitors.monitoring.coreos.com
      # - probes.monitoring.coreos.com
      # - prometheuses.monitoring.coreos.com
      # - prometheusrules.monitoring.coreos.com
      # - servicemonitors.monitoring.coreos.com
      # - thanosrulers.monitoring.coreos.com
      waitForRollouts:
      # Need to wait for istiod otherwise subsequent webhook invocations will fail.
      - istio-system/istiod
