apiVersion: api.00rg.com/v1alpha1
kind: Wave
metadata:
  name: wave3
spec:
  hooks:
    preApply:
      waitForRollouts:
      # Need to wait for istiod otherwise subsequent webhook invocations will fail.
      - istio-system/istiod
