apiVersion: apps/v1
kind: Deployment
metadata:
  name: baz
  labels:
    app: baz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baz
  template:
    metadata:
      labels:
        app: baz
    spec:
      serviceAccountName: baz
      containers:
      - name: hello
        image: k3d-local-registry:5555/hello:0.0.1
        imagePullPolicy: Always
        env:
        - name: EXTERNAL_URL
          value: http://httpbin.httpbin.svc.cluster.local/get
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://tracing.grafana-stack:4318/v1/traces
