apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
labels: []
# Below example interfer with some generated ServiceMonitor (e.g. Tempo's) that expect
# the value of app.kubernetes.io/managed-by to equal "Helm".
# - pairs:
#     app.kubernetes.io/managed-by: 00org-state
