apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- namespace.yaml
- kube-prometheus-crds.gen.yaml
- grafana-agent-operator.gen.yaml
- m3db-operator.gen.yaml
