apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  profile: default
  components:
    # Disabled the pre-canned ingress gateway in the default profile.
    ingressGateways:
    - enabled: false
      name: istio-ingressgateway
  values:
    istio_cni:
      # Removes need for elevated RBAC permissions.
      # See: https://istio.io/latest/docs/setup/additional-setup/cni
      # enabled: true
      #
      # TODO: overlay this locally - doesn't seem to work with k3d.
      enabled: false
    sidecarInjectorWebhook:
      # Inject by default.
      enableNamespacesByDefault: true
    meshConfig:
      # Forward traces to directly to Tempo. Grafana Operator doesn't support tracing
      # yet so if we don't forward directly to Tempo we'll need to install a Grafana Agent
      # using another mechanism or install an OTLP collector or similar.
      # See: https://github.com/grafana/agent/issues/1044
      enableTracing: true
      defaultConfig:
        tracing:
          sampling: 100
          # Using OpenCensus instead of Zipkin for compatability with OTEL?
          # See https://github.com/istio/istio/issues/23960
          openCensusAgent:
            address: tempo.grafana-stack:55678
          # zipkin:
          #   address: tempo.grafana-stack:9411
