# Inspired by https://github.com/istio/istio/blob/c48ce2e7777dd268c3aa73e2ce122820da3c52a0/samples/addons/extras/prometheus-operator.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: grafana-stack
  labels:
    grafana-agent-metrics-instance: istio
spec:
  jobLabel: istiod
  targetLabels: [app]
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
    - {key: istio, operator: In, values: [pilot]}
  endpoints:
  - port: http-monitoring
    interval: 15s
