apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: Don't blanket set the namespace across all resources as some such as the
# Prometheus exporters rely on being placed in other namespaces such as kube-system.

resources:
- kube-prometheus.gen.yaml
- loki.gen.yaml
- tempo.gen.yaml
- virtual-services.yaml

# Custom resources reconciled by grafana-agent-operator.
- default-grafana-agent.yaml
- default-metrics-instance.yaml
- default-logs-instance.yaml
- default-pod-logs.yaml
- istio-grafana-agent.yaml
- istio-metrics-instance.yaml
- istio-pod-monitor.yaml
- istio-prometheus-rule.yaml
- tracing-grafana-agent.yaml
- grafana-agent-monitoring.yaml

patches:
# Add the grafana-agent-metrics-instance=default label to all remaining ServiceMonitors.
# The remaining ServiceMonitors will be associated with workloads that are specifically NOT
# injected with an Istio sidecar. These workloads will be: Prometheus/Grafana agents,
# kube-system workloads, and things like node-exporter which use host networking and so
# are also not injected.
- patch: |-
    - op: add
      path: /metadata/labels/grafana-agent-metrics-instance
      value: default
  target:
    group: monitoring.coreos.com
    kind: ServiceMonitor
