apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      serviceAccountName: bar
      containers:
      - name: hello
        image: k3d-local-registry:5555/hello:0.0.1
        imagePullPolicy: Always
        env:
        - name: EXTERNAL_URL
          value: http://baz.baz.svc.cluster.local/external
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://tracing.monitoring:4318/v1/traces
